version: '3'
services:
  backend:
    build:
      context: ./lythar-backend/
      dockerfile: LytharBackend/Dockerfile
    container_name: lythar-backend
    ports:
      - "8080:8080"
  web:
    build:
      context: ./lythar-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: lythar-frontend