version: '3'

# TO-DO: Replace the networks with secure contained networks when we get nginx working

services:
  frontend:
    container_name: lythar-frontend

    build:
      context: ${FRONTEND_PATH}
      dockerfile: dev.Dockerfile

    environment:
      ENV_VARIABLE: ${FRONTEND_PATH}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
      CHOKIDAR_USEPOLLING: true
      WATCHPACK_POLLING: true

    env_file:
      - ./.env

    network_mode: bridge

    volumes:
      - ${FRONTEND_PATH}/src:/app/src
      - ${FRONTEND_PATH}public:/app/public

    restart: always
    ports:
      - "3000:3000"

  backend:
    container_name: lythar-backend

    build:
      context: ${BACKEND_PATH}
      dockerfile: LytharBackend/Dockerfile

    restart: always
    network_mode: bridge

    ports:
      - "8080:8080"
  docs:
    container_name: lythar-vitepress

    build:
      context: ${DOCS_PATH}
      dockerfile: dev.Dockerfile

    environment:
      CHOKIDAR_USEPOLLING: true
      WATCHPACK_POLLING: true

    volumes:
      - ./packages/docs/docs:/app/docs

    network_mode: bridge

    restart: always
    ports:
      - "3001:3001"